#!/usr/bin/env sh
# freebsd-pkg-cache.sh — build an offline install cache for EduOS FreeBSD
#
# Fetches:
#   1. FreeBSD pkg(8) packages    -> <CACHE_DIR>/pkg/
#   2. Python wheels (pip download) -> <CACHE_DIR>/wheels/
# and generates <CACHE_DIR>/install-offline.sh which installs everything
# from the local cache without internet access.
#
# Usage:
#   sh Scripts/freebsd-pkg-cache.sh [cache_dir]
#
# Default cache_dir: /opt/eduos-packages
# Deploy: copy the cache into the ISO rootfs before the ISO build step
# (rootfs/opt/eduos-packages/), or rsync it to a lab machine.

set -u

CACHE_DIR="${1:-/opt/eduos-packages}"
PKG_DIR="$CACHE_DIR/pkg"
WHEEL_DIR="$CACHE_DIR/wheels"
PKG_LIST="$(dirname "$0")/../Packages/freebsd-packages.txt"

# Core runtime packages installed on every EduOS machine
PKGS="python311 py311-pip git curl wget bash nano"
# Python modules required by EduOS (mirrors the first-boot installer)
PIP_PKGS="cryptography fastapi uvicorn websockets psutil pyjwt bcrypt slowapi"

echo "[EduOS] Cache dir: $CACHE_DIR"

if [ "$(id -u)" -ne 0 ]; then
    echo "[EduOS] Note: run as root on FreeBSD to fetch pkg(8) packages."
fi

mkdir -p "$PKG_DIR" "$WHEEL_DIR"

# ---------- 1. FreeBSD pkg(8) packages ----------
if command -v pkg >/dev/null 2>&1; then
    echo "[EduOS] Fetching FreeBSD packages..."
    env ASSUME_ALWAYS_YES=YES pkg update -q || true
    pkg fetch -y -d -o "$PKG_DIR" $PKGS || \
        echo "[EduOS] WARNING: pkg fetch failed; continuing with wheels only."
else
    echo "[EduOS] WARNING: pkg(8) not found - skipping FreeBSD packages."
    if [ -f "$PKG_LIST" ]; then
        echo "[EduOS] Package manifest available at: $PKG_LIST"
    fi
fi

# ---------- 2. Python wheels ----------
if command -v pip3.11 >/dev/null 2>&1; then
    PIP="pip3.11"
elif command -v pip3 >/dev/null 2>&1; then
    PIP="pip3"
else
    echo "[EduOS] ERROR: no pip3.11/pip3 found. Install python311 first."
    exit 1
fi

echo "[EduOS] Fetching Python wheels..."
"$PIP" download $PIP_PKGS \
    --dest "$WHEEL_DIR" \
    --only-binary=:all: \
    --platform manylinux_2_17_x86_64 \
    --python-version 311 \
    --implementation cp \
    --abi cp311 2>/dev/null || \
"$PIP" download $PIP_PKGS --dest "$WHEEL_DIR" 2>/dev/null || \
    echo "[EduOS] WARNING: wheel download failed (offline? mirror issue?)."

echo "[EduOS] Wheels cached: $(ls "$WHEEL_DIR" 2>/dev/null | wc -l)"

# ---------- 3. Offline installer ----------
cat > "$CACHE_DIR/install-offline.sh" << 'INSTALL_EOF'
#!/bin/sh
# install-offline.sh — install EduOS dependencies from the local cache.
# Generated by Scripts/freebsd-pkg-cache.sh — do not edit by hand.
CACHE_DIR="$(dirname "$0")"
PKG_DIR="$CACHE_DIR/pkg"
WHEEL_DIR="$CACHE_DIR/wheels"

# FreeBSD pkg(8) from local cache (with dependencies resolved)
if [ -d "$PKG_DIR" ] && [ "$(ls "$PKG_DIR" 2>/dev/null | wc -l)" -gt 0 ]; then
    echo "[EduOS] Installing FreeBSD packages from cache..."
    env ASSUME_ALWAYS_YES=YES pkg add "$PKG_DIR"/*.txz 2>/dev/null || \
        env ASSUME_ALWAYS_YES=YES pkg add "$PKG_DIR"/* 2>/dev/null || true
else
    echo "[EduOS] No pkg cache found; skipping (online install may be used)."
fi

# Python wheels from local cache
if [ -d "$WHEEL_DIR" ] && [ "$(ls "$WHEEL_DIR" 2>/dev/null | wc -l)" -gt 0 ]; then
    echo "[EduOS] Installing Python packages from wheel cache..."
    pip3.11 install --no-index --find-links="$WHEEL_DIR" \
        cryptography fastapi uvicorn websockets psutil pyjwt bcrypt slowapi 2>/dev/null || \
        pip3.11 install "$WHEEL_DIR"/*.whl 2>/dev/null || true
else
    echo "[EduOS] No wheel cache found; trying internet..."
    pip3.11 install --quiet cryptography fastapi uvicorn websockets psutil pyjwt bcrypt slowapi || true
fi

echo "[EduOS] Offline install complete."
INSTALL_EOF

chmod +x "$CACHE_DIR/install-offline.sh"

echo "[EduOS] Done."
echo "[EduOS]   pkg cache : $PKG_DIR"
echo "[EduOS]   wheels    : $WHEEL_DIR"
echo "[EduOS]   installer : $CACHE_DIR/install-offline.sh"
echo "[EduOS] Deploy: copy '$CACHE_DIR' to the ISO rootfs at"
echo "[EduOS]   rootfs/opt/eduos-packages/ before the ISO build step."
